### ISSUE TITLE
Using JLINK to write firmware succeeded, but could not run in ZigBee 2mqtt

### ISSUE THREAD

**Issue by unpack8866** [egony/cc2652p_E72-2G4M20S1E#11]
Using JLINK to write firmware succeeded, but could not run in ZigBee 2mqtt
![QQ图片20210219231115](https://user-images.githubusercontent.com/40196105/108522500-dcb8dc80-7307-11eb-8929-dfef63ab4562.png)

**Comment by suifeng009** [comment]
配置文件写错了吧，linux正常是能直接识别，群晖加载驱动了也不行~
