### ISSUE TITLE
Questions about firmware

### ISSUE THREAD

**Issue by glsf91** [egony/cc2652p_E72-2G4M20S1E#14]
Thanks for you great designs. Very appreciated.

I have a few questions about the firmware:

You wrote:
"Coordinator backup from 2538/2652/1352 can be loaded back into another 2538/2652/1352, but into CLEAN (never used with zigbee2mqtt) chip only. You can clear chip with zigbee2mqtt script scripts\zStackEraseAllNvMem.js"

1. What do you mean with coordinator backup ?

You wrote:
"As I know, sharing source codes prohibited by TI, so there is no sources here. And I can't made patches because they will include code. But you now what to do ;)"

2. Are you sure, because Koenkk is also sharing his patches. I can also download TI source code from TI site. I'am interested in your patches.
3. I don't understand what you mean with "But you now what to do" ?

You wrote:
"One of the features of this module is that it uses generator and RF-Switch settings that are not compatible with Koenkk's Launchpad firmware ."
and "Koenkk now also supports this module in their firmwares . "

4. Do you know if in the current koenkk firmware (Zigbeer E72 by Egony) the generator and RF-Switch settings  are compatible now?

**Comment by egony** [comment]
1. File data\coordinator_backup.json
2. I have no patches. Just source codes. Koenkk shares patches - it is not prohibited.
3. Just ask.
4. Yes
