### ISSUE TITLE
Alternative flashing

### ISSUE THREAD

**Issue by McGiverGim** [egony/cc2652p_E72-2G4M20S1E#17]
Hi! Thanks for your great work with this. 

I only want to know if the use of the script `cc2538-bsl.py` is mandatory for flashing, or you simply recommend it because it is open source and you have tested it but I can use other tools like the TI SmartRF Flash Programmer v2 or uniflash or there is something in the hardware that limits the tools to use...

Thanks in advance!

**Comment by egony** [comment]
Hi!
You can use any software for flashing. 
cc2538-bsl.py mandatory only for auto-bsl boards.
