### ISSUE TITLE
zigbee-herdsman supportsLED patch no longer needed

### ISSUE THREAD

**Issue by matbech** [egony/cc2652p_E72-2G4M20S1E#24]
The patch described here:
https://github.com/egony/cc2652p_E72-2G4M20S1E/blob/master/firmware/coordinator/README.md

```
Leds can be turned OFF by zigbee2mqtt config, but on March 2021 you need to modify file zStackAdapter.js:

supportsLED() {
    return __awaiter(this, void 0, void 0, function* () {
      return true; //this.version.product !== tstype_1.ZnpVersion.zStack3x0; // <---- change like this
    });
```

Doesn't seem to be necessary anymore with the latest version of zigbee-herdsman:
```
        const zStack3x0 = this.version.product === ZnpVersion.zStack3x0;
        this.supportsLED_ = !zStack3x0 || (zStack3x0 && parseInt(this.version.revision) >= 20210430);
```
https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/z-stack/adapter/zStackAdapter.ts#L116

The README.md can probably be updated.

**Comment by egony** [comment]
Hi!
Yes, true. But my firmware siill  <20210430 :)))
So I must update firmware first.

**Comment by matbech** [comment]
Oh that would be much appreciated :-)

**Comment by Symbol84** [comment]
Green LED does not work after update 20210813.

**Comment by egony** [comment]
> Green LED does not work after update 20210813. Turned on and off "Disable led" nothing changes

LEDs fails on some installations (e.g. on Windows all LEDs works fine). Why? I do not know, so now firmware 20210813 removed.

**Comment by egony** [comment]
LEDs fails becuse z2m support too bad. New patch instruction added.
