### ISSUE TITLE
Zigbee2MQTT:error - Failed to set permit join to true

### ISSUE THREAD

**Issue by sergey-suloev** [egony/cc2652p_E72-2G4M20S1E#33]
Zigbee2MQTT:warn 2021-12-21 12:22:59: permit_join set to true in configuration.yaml.
Zigbee2MQTT:warn 2021-12-21 12:22:59: Allowing new devices to join.
Zigbee2MQTT:warn 2021-12-21 12:22:59: Set permit_join to false once you joined all devices.
Zigbee2MQTT:info 2021-12-21 12:22:59: Zigbee: allowing new devices to join.
Zigbee2MQTT:error 2021-12-21 12:22:59: Failed to set permit join to true

**Comment by sergey-suloev** [comment]
This is not a fake but a real issue

**Comment by sergey-suloev** [comment]
Used firmware CC2652P_E72_20210319

**Comment by egony** [comment]
> This is not a fake but a real issue. It happens very often with latest Zigbee2MQTT. So take a look at it.

Why? Failed to set permit join to true in log not means that permit join is not set to true.

**Comment by bcdonadio** [comment]
If I may, I think I saw this issue a few times in the last weeks (no logs right now, sorry, but I'll keep an eye). I think it's more likely caused by the GUI of Z2MQTT failing internally to perform this action instead of something to do with the firmware.

There was a supposedly solved bug not so long ago that it failed to do that selectively (just for the controller or for a single router).

**Comment by bcdonadio** [comment]
And also IIRC, with ZB3.0, Z2MQTT would change your permit_join to false after starting anyway.

**Comment by sergey-suloev** [comment]
> If I may, I think I saw this issue a few times in the last weeks (no logs right now, sorry, but I'll keep an eye). I think it's more likely caused by the GUI of Z2MQTT failing internally to perform this action instead of something to do with the firmware.
> 
> There was a supposedly solved bug not so long ago that it failed to do that selectively (just for the controller or for a single router).

if you are sure that it is not a firmware bug then the issue can be closed
