### ISSUE TITLE
new fw version

### ISSUE THREAD

**Issue by Theoreet** [egony/cc2652p_E72-2G4M20S1E#34]
Is there somebody who can/would compile an newer firmware version ? This because of the battery drain issue (Ikea remotes)

**Comment by egony** [comment]
> battery drain issue (Ikea remotes)

How is the battery drain and stick firmware related?

**Comment by Theoreet** [comment]
> > battery drain issue (Ikea remotes)
> 
> How is the battery drain and stick firmware related?

There seems to be some fw problems
[(https://github.com/Koenkk/zigbee2mqtt/issues/3444)](url)

[https://community.home-assistant.io/t/ikea-tradfri-batteries-in-the-remote-controls-are-quickly-discharged/109185/142](url)
