### ISSUE TITLE
Прошивка для координатора cc2652p_E72-2G4M20S1E

### ISSUE THREAD

**Issue by vit-um** [egony/cc2652p_E72-2G4M20S1E#37]
В папке cc2652p_E72-2G4M20S1E/firmware/coordinator/ находится прошивка  znp_CC1352P_E72_20220301.zip с подозрительным названием CC**13**52P нет ли здесь ошибки? 

Ею точно можно перепрошивать CC2652 стик?

**Comment by egony** [comment]
Да.

**Comment by vit-um** [comment]
Из этих трех прошивок, стабильной на моем стике CC2652 оказалась только та что 21 года:
znp_CC1352P_E72_20220301.hex
znp_CC2652P_E72_20220217.hex
znp_CC2652P_E72_sdk_5_10_00_48_20210813.hex

На остальных в устройства сыпали в логи ошибками, жаль не сохранилось истории, чтобы Вам отправить.
