### ISSUE TITLE
What is the latest CC2662p firmware to use (file deleted)

### ISSUE THREAD

**Issue by Theoreet** [egony/cc2652p_E72-2G4M20S1E#40]
I want to update to the last available firmware, but there's only  the "__Delete znp_CC2652P_E72_20220217.zi_p_" so what's the latest functional version for now 
Also because there none older version anymore on the github

**Comment by egony** [comment]
Latest firmware here: https://github.com/egony/cc2652p_E72-2G4M20S1E/tree/master/firmware/coordinator
