### ISSUE TITLE
How to turn off the LED（board work fine）

### ISSUE THREAD

**Issue by maYunLaoXi** [egony/cc2652p_E72-2G4M20S1E#42]
The LED on the board is always on (see the picture).It's too bright on my bedroom at night.Can I turn off it  by configuration ？

my env：zigbee2mqtt at docker; flash the coordinator [znp_CC1352P_E72_20220301.zip](https://github.com/egony/cc2652p_E72-2G4M20S1E/blob/master/firmware/coordinator/znp_CC1352P_E72_20220301.zip)

<img width="436" alt="CDD4CF4C-38BF-4BFF-956C-29EB54D1ED27" src="https://user-images.githubusercontent.com/52158968/177260263-bc90b766-fd10-4f5a-a3ee-ec2dfd2fe810.PNG">

**Comment by Damianod27** [comment]
Hello.  In the configuration.yaml file, try using the disable_led: true command.  Write it between serial: and port: /dev/ttyACM0.  

Example: 

Command in the terminal : nano /opt/zigbee2mqtt/data/configuration.yaml

serial: 
disable_led: true 
port: /dev/ttyACM0


Let me know if it worked

Regards
