### ISSUE TITLE
Excuse me, what do these two LEDs mean? 

### ISSUE THREAD

**Issue by meijie-jesse** [egony/cc2652p_E72-2G4M20S1E#5]
Excuse me, what do these two LEDs mean? thank you!
I tried to find the answer in the design of the V3 board, but failed.

In README.md, I found that:
LEDs description:
- LED4 (Green) turns ON when High-power PA is not used (TX power from -20 to 5 dBm)
- LED3 (Red) turns ON when High-power PA is used (TX power from 15 to 20 dBm)
- LED1,2 supported in source code, but currently not used and perhaps never will be used.
- Leds can't be turned OFF by zigbee2mqtt config - sorry, I haven't skills for it.

But it doesn't seem to match v4.

**Comment by egony** [comment]
Take a look at firmware description in firmware section.
